### ISSUE TITLE
ES module

### ISSUE THREAD

**Issue by Desttro** [DSergiu/vanilla-hcaptcha#18]
Hello,
When using this package with Astro, I am getting this message:

`vanilla-hcaptcha doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`

**Comment by DSergiu** [comment]
Hi. This is built as an IIFE. You should be able to do the following:

```html
<script src="https://cdn.jsdelivr.net/npm/vanilla-hcaptcha"></script>
```

or if you installed via npm/yarn:

```html
<script src="vanilla-hcaptcha"></script>
```

If this does not help, please provide a snippet to reproduce the error.

**Comment by DSergiu** [comment]
Closing this.
