### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by dcantatore** [DSergiu/vanilla-hcaptcha#2]
Is it possible to add a way to easily trigger the hcaptcha window functions like window.hcaptcha.reset(), etc? 

I feel like this could make it even easier for some people.

Also in the documentation you may want to add the expired event as an example.

**Comment by DSergiu** [comment]
Deployed 0.0.5. Thank you for the feature idea. 

The `expired` event is not different than the other exemplified events and thus there is no reason to clutter the `README` even further.
